export interface HiraganaCard {
  id: number;
  character: string;
  romanji: string;
  example: string;
  meaning: string;
}

export const hiragana: HiraganaCard[] = [
  {
    id: 1,
    character: "あ",
    romanji: "a",
    example: "あいさつ",
    meaning: "Greeting",
  },
  {
    id: 2,
    character: "い",
    romanji: "i",
    example: "いえ",
    meaning: "House",
  },
  {
    id: 3,
    character: "う",
    romanji: "u",
    example: "うみ",
    meaning: "Sea",
  },
  {
    id: 4,
    character: "え",
    romanji: "e",
    example: "えんぴつ",
    meaning: "Pencil",
  },
  {
    id: 5,
    character: "お",
    romanji: "o",
    example: "おかね",
    meaning: "Money",
  },
  {
    id: 6,
    character: "か",
    romanji: "ka",
    example: "かさ",
    meaning: "Umbrella",
  },
  {
    id: 7,
    character: "き",
    romanji: "ki",
    example: "きんぎょ",
    meaning: "Goldfish",
  },
  {
    id: 8,
    character: "く",
    romanji: "ku",
    example: "くつ",
    meaning: "Shoes",
  },
  {
    id: 9,
    character: "け",
    romanji: "ke",
    example: "けいたいでんわ",
    meaning: "Mobile phone",
  },
  {
    id: 10,
    character: "こ",
    romanji: "ko",
    example: "こども",
    meaning: "Child",
  },
  {
    id: 11,
    character: "さ",
    romanji: "sa",
    example: "さくら",
    meaning: "Cherry blossom",
  },
  {
    id: 12,
    character: "し",
    romanji: "shi",
    example: "しんぶん",
    meaning: "Newspaper",
  },
  {
    id: 13,
    character: "す",
    romanji: "su",
    example: "すし",
    meaning: "Sushi",
  },
  {
    id: 14,
    character: "せ",
    romanji: "se",
    example: "せんせい",
    meaning: "Teacher",
  },
  {
    id: 15,
    character: "そ",
    romanji: "so",
    example: "そら",
    meaning: "Sky",
  },
  {
    id: 16,
    character: "た",
    romanji: "ta",
    example: "たけ",
    meaning: "Bamboo",
  },
  {
    id: 17,
    character: "ち",
    romanji: "chi",
    example: "ちず",
    meaning: "Map",
  },
  {
    id: 18,
    character: "つ",
    romanji: "tsu",
    example: "つくえ",
    meaning: "Desk",
  },
  {
    id: 19,
    character: "て",
    romanji: "te",
    example: "てがみ",
    meaning: "Letter",
  },
  {
    id: 20,
    character: "と",
    romanji: "to",
    example: "とけい",
    meaning: "Clock",
  },
  {
    id: 21,
    character: "な",
    romanji: "na",
    example: "なつ",
    meaning: "Summer",
  },
  {
    id: 22,
    character: "に",
    romanji: "ni",
    example: "にわ",
    meaning: "Garden",
  },
  {
    id: 23,
    character: "ぬ",
    romanji: "nu",
    example: "ぬま",
    meaning: "Swamp",
  },
  {
    id: 24,
    character: "ね",
    romanji: "ne",
    example: "ねこ",
    meaning: "Cat",
  },
  {
    id: 25,
    character: "の",
    romanji: "no",
    example: "のみもの",
    meaning: "Drink",
  },
  {
    id: 26,
    character: "は",
    romanji: "ha",
    example: "はな",
    meaning: "Flower",
  },
  {
    id: 27,
    character: "ひ",
    romanji: "hi",
    example: "ひこうき",
    meaning: "Airplane",
  },
  {
    id: 28,
    character: "ふ",
    romanji: "fu",
    example: "ふじさん",
    meaning: "Mount Fuji",
  },
  {
    id: 29,
    character: "へ",
    romanji: "he",
    example: "へや",
    meaning: "Room",
  },
  {
    id: 30,
    character: "ほ",
    romanji: "ho",
    example: "ほん",
    meaning: "Book",
  },
  {
    id: 31,
    character: "ま",
    romanji: "ma",
    example: "まど",
    meaning: "Window",
  },
  {
    id: 32,
    character: "み",
    romanji: "mi",
    example: "みせ",
    meaning: "Shop",
  },
  {
    id: 33,
    character: "む",
    romanji: "mu",
    example: "むし",
    meaning: "Insect",
  },
  {
    id: 34,
    character: "め",
    romanji: "me",
    example: "めがね",
    meaning: "Glasses",
  },
  {
    id: 35,
    character: "も",
    romanji: "mo",
    example: "もも",
    meaning: "Peach",
  },
  {
    id: 36,
    character: "や",
    romanji: "ya",
    example: "やま",
    meaning: "Mountain",
  },
  {
    id: 37,
    character: "ゆ",
    romanji: "yu",
    example: "ゆき",
    meaning: "Snow",
  },
  {
    id: 38,
    character: "よ",
    romanji: "yo",
    example: "よる",
    meaning: "Night",
  },
  {
    id: 39,
    character: "ら",
    romanji: "ra",
    example: "らいねん",
    meaning: "Next year",
  },
  {
    id: 40,
    character: "り",
    romanji: "ri",
    example: "りんご",
    meaning: "Apple",
  },
  {
    id: 41,
    character: "る",
    romanji: "ru",
    example: "るす",
    meaning: "Absence",
  },
  {
    id: 42,
    character: "れ",
    romanji: "re",
    example: "れきし",
    meaning: "History",
  },
  {
    id: 43,
    character: "ろ",
    romanji: "ro",
    example: "ろうそく",
    meaning: "Candle",
  },
  {
    id: 44,
    character: "わ",
    romanji: "wa",
    example: "わたし",
    meaning: "I",
  },
  {
    id: 45,
    character: "を",
    romanji: "wo",
    example: "をたべます",
    meaning: "Eat (object marker)",
  },
  {
    id: 46,
    character: "ん",
    romanji: "n",
    example: "でんわ",
    meaning: "Telephone",
  },
];
