export interface KatakanaCard {
  id: number;
  character: string;
  romaji: string;
  example: string;
  meaning: string;
}

export const katakana: KatakanaCard[] = [
  {
    id: 1,
    character: "ア",
    romaji: "a",
    example: "アメリカ",
    meaning: "アメリカ",
  },
  {
    id: 2,
    character: "イ",
    romaji: "i",
    example: "イタリア",
    meaning: "イタリア",
  },
  {
    id: 3,
    character: "ウ",
    romaji: "u",
    example: "ウクライナ",
    meaning: "ウクライナ",
  },
  {
    id: 4,
    character: "エ",
    romaji: "e",
    example: "エジプト",
    meaning: "エジプト",
  },
  {
    id: 5,
    character: "オ",
    romaji: "o",
    example: "オーストラリア",
    meaning: "オーストラリア",
  },
  {
    id: 6,
    character: "カ",
    romaji: "ka",
    example: "カナダ",
    meaning: "カナダ",
  },
  {
    id: 7,
    character: "キ",
    romaji: "ki",
    example: "キューバ",
    meaning: "キューバ",
  },
  {
    id: 8,
    character: "ク",
    romaji: "ku",
    example: "クウェート",
    meaning: "クウェート",
  },
  {
    id: 9,
    character: "ケ",
    romaji: "ke",
    example: "ケニア",
    meaning: "ケニア",
  },
  {
    id: 10,
    character: "コ",
    romaji: "ko",
    example: "コロンビア",
    meaning: "コロンビア",
  },
  {
    id: 11,
    character: "サ",
    romaji: "sa",
    example: "サウジアラビア",
    meaning: "サウジアラビア",
  },
  {
    id: 12,
    character: "シ",
    romaji: "shi",
    example: "シンガポール",
    meaning: "シンガポール",
  },
  {
    id: 13,
    character: "ス",
    romaji: "su",
    example: "スウェーデン",
    meaning: "スウェーデン",
  },
  {
    id: 14,
    character: "セ",
    romaji: "se",
    example: "セネガル",
    meaning: "セネガル",
  },
  {
    id: 15,
    character: "ソ",
    romaji: "so",
    example: "ソマリア",
    meaning: "ソマリア",
  },
  {
    id: 16,
    character: "タ",
    romaji: "ta",
    example: "タイ",
    meaning: "タイ",
  },
  {
    id: 17,
    character: "チ",
    romaji: "chi",
    example: "チリ",
    meaning: "チリ",
  },
  {
    id: 18,
    character: "ツ",
    romaji: "tsu",
    example: "ツバル",
    meaning: "ツバル",
  },
  {
    id: 19,
    character: "テ",
    romaji: "te",
    example: "テュニジア",
    meaning: "テュニジア",
  },
  {
    id: 20,
    character: "ト",
    romaji: "to",
    example: "トルコ",
    meaning: "トルコ",
  },
  {
    id: 21,
    character: "ナ",
    romaji: "na",
    example: "ナイジェリア",
    meaning: "ナイジェリア",
  },
  {
    id: 22,
    character: "ニ",
    romaji: "ni",
    example: "ニュージーランド",
    meaning: "ニュージーランド",
  },
  {
    id: 23,
    character: "ヌ",
    romaji: "nu",
    example: "ヌエバジョンダ",
    meaning: "ヌエバジョンダ",
  },
  {
    id: 24,
    character: "ネ",
    romaji: "ne",
    example: "ネパール",
    meaning: "ネパール",
  },
  {
    id: 25,
    character: "ノ",
    romaji: "no",
    example: "ノルウェー",
    meaning: "ノルウェー",
  },
  {
    id: 26,
    character: "ハ",
    romaji: "ha",
    example: "ハンガリー",
    meaning: "ハンガリー",
  },
  {
    id: 27,
    character: "ヒ",
    romaji: "hi",
    example: "ヒンディー",
    meaning: "ヒンディー",
  },
  {
    id: 28,
    character: "フ",
    romaji: "fu",
    example: "フィリピン",
    meaning: "フィリピン",
  },
  {
    id: 29,
    character: "ヘ",
    romaji: "he",
    example: "ヘルシンキ",
    meaning: "ヘルシンキ",
  },
  {
    id: 30,
    character: "ホ",
    romaji: "ho",
    example: "ホンジュラス",
    meaning: "ホンジュラス",
  },
  {
    id: 31,
    character: "マ",
    romaji: "ma",
    example: "マレーシア",
    meaning: "マレーシア",
  },
  {
    id: 32,
    character: "ミ",
    romaji: "mi",
    example: "ミャンマー",
    meaning: "ミャンマー",
  },
  {
    id: 33,
    character: "ム",
    romaji: "mu",
    example: "ムスクワ",
    meaning: "ムスクワ",
  },
  {
    id: 34,
    character: "メ",
    romaji: "me",
    example: "メキシコ",
    meaning: "メキシコ",
  },
  {
    id: 35,
    character: "モ",
    romaji: "mo",
    example: "モロッコ",
    meaning: "モロッコ",
  },
  {
    id: 36,
    character: "ヤ",
    romaji: "ya",
    example: "ヤマト",
    meaning: "ヤマト",
  },
  {
    id: 37,
    character: "ユ",
    romaji: "yu",
    example: "ユーゴスラビア",
    meaning: "ユーゴスラビア",
  },
  {
    id: 38,
    character: "ヨ",
    romaji: "yo",
    example: "ヨルダン",
    meaning: "ヨルダン",
  },
  {
    id: 39,
    character: "ラ",
    romaji: "ra",
    example: "ラトビア",
    meaning: "ラトビア",
  },
  {
    id: 40,
    character: "リ",
    romaji: "ri",
    example: "リトアニア",
    meaning: "リトアニア",
  },
  {
    id: 41,
    character: "ル",
    romaji: "ru",
    example: "ルーマニア",
    meaning: "ルーマニア",
  },
  {
    id: 42,
    character: "レ",
    romaji: "re",
    example: "レバノン",
    meaning: "レバノン",
  },
  {
    id: 43,
    character: "ロ",
    romaji: "ro",
    example: "ロシア",
    meaning: "ロシア",
  },
  {
    id: 44,
    character: "ワ",
    romaji: "wa",
    example: "ワシントン",
    meaning: "ワシントン",
  },
  {
    id: 45,
    character: "ヲ",
    romaji: "wo",
    example: "ヲタク",
    meaning: "ヲタク",
  },
  {
    id: 46,
    character: "ン",
    romaji: "n",
    example: "インド",
    meaning: "インド",
  },
];
